name: Run analyze and tests
on: pull_request
jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: App dependencies
        run: flutter pub get
      - name: Formatting issues (App)
        run: flutter format -n --set-exit-if-changed .     
       name: Build APK
        run: flutter build apk --debug
      - name: Analyze code (App)
        run: flutter analyze
